import { Language } from "./types";

export const TRANSLATIONS: Record<Language, any> = {
  'sr-Cyrl': {
    title: 'Радна биографија',
    personalInfo: 'Лични подаци',
    education: 'Образовање',
    workExperience: 'Радно искуство',
    skills: 'Вештине',
    itSkills: 'IT вештине',
    additionalSkills: 'Додатне вештине',
    languages: 'Страни језици',
    other: 'Остало',
    firstName: 'Име',
    lastName: 'Презиме',
    dateOfBirth: 'Датум рођења',
    address: 'Адреса',
    phone: 'Телефон',
    email: 'Е-пошта',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Веб-сајт',
    institution: 'Назив установе',
    field: 'Смер / вештине',
    employer: 'Послодавац',
    city: 'Место рада',
    country: 'Држава',
    jobTitle: 'Радно место',
    jobDescription: 'Опис посла',
    languageName: 'Језик',
    level: 'Ниво',
    driversLicense: 'Возачка дозвола',
    relocation: 'Рад ван места пребивалишта',
    availability: 'Доступан одмах',
    addEducation: 'Додај образовање',
    addWork: 'Додај радно место',
    addSkill: 'Додај вештину',
    addLanguage: 'Додај језик',
    addOther: 'Додај информацију',
    preview: 'Преглед',
    downloadPdf: 'Преузми PDF',
    from: 'Од',
    to: 'До',
    present: 'тренутно',
    currently: 'тренутно',
    saved: 'Сачувано',
    saving: 'Чува се...',
    notSaved: 'Није сачувано',
    incognitoWarning: 'Радите у приватном режиму — подаци неће бити сачувани по затварању прозора.',
    datePlaceholder: 'ДД.ММ.ГГГГ.',
    confirmDeleteTitle: 'Потврда брисања',
    confirmDeleteMessage: 'Да ли сте сигурни да желите да обришете ову ставку?',
    confirmDeleteAction: 'Обриши',
    cancelAction: 'Откажи',
    livePreview: 'Преглед уживо',
    selectTemplate: 'Изабери шаблон',
    modern: 'Модеран',
    classic: 'Класичан',
    minimalist: 'Минималистички',
  },
  'sr-Latn': {
    title: 'Radna biografija',
    personalInfo: 'Lični podaci',
    education: 'Obrazovanje',
    workExperience: 'Radno iskustvo',
    skills: 'Veštine',
    itSkills: 'IT veštine',
    additionalSkills: 'Dodatne veštine',
    languages: 'Strani jezici',
    other: 'Ostalo',
    firstName: 'Ime',
    lastName: 'Prezime',
    dateOfBirth: 'Datum rođenja',
    address: 'Adresa',
    phone: 'Telefon',
    email: 'E-pošta',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Veb-sajt',
    institution: 'Naziv ustanove',
    field: 'Smer / veštine',
    employer: 'Poslodavac',
    city: 'Mesto rada',
    country: 'Država',
    jobTitle: 'Radno mesto',
    jobDescription: 'Opis posla',
    languageName: 'Jezik',
    level: 'Nivo',
    driversLicense: 'Vozačka dozvola',
    relocation: 'Rad van mesta prebivališta',
    availability: 'Dostupan odmah',
    addEducation: 'Dodaj obrazovanje',
    addWork: 'Dodaj radno mesto',
    addSkill: 'Dodaj veštinu',
    addLanguage: 'Dodaj jezik',
    addOther: 'Dodaj informaciju',
    preview: 'Pregled',
    downloadPdf: 'Preuzmi PDF',
    from: 'Od',
    to: 'Do',
    present: 'trenutno',
    currently: 'trenutno',
    saved: 'Sačuvano',
    saving: 'Čuva se...',
    notSaved: 'Nije sačuvano',
    incognitoWarning: 'Radite u privatnom režimu — podaci neće biti sačuvani po zatvaranju prozora.',
    datePlaceholder: 'DD.MM.YYYY.',
    confirmDeleteTitle: 'Potvrda brisanja',
    confirmDeleteMessage: 'Da li ste sigurni da želite da obrišete ovu stavku?',
    confirmDeleteAction: 'Obriši',
    cancelAction: 'Otkaži',
    livePreview: 'Pregled uživo',
    selectTemplate: 'Izaberi šablon',
    modern: 'Moderan',
    classic: 'Klasičan',
    minimalist: 'Minimalistički',
  },
  'en': {
    title: 'Curriculum Vitae',
    personalInfo: 'Personal Information',
    education: 'Education',
    workExperience: 'Work Experience',
    skills: 'Skills',
    itSkills: 'IT Skills',
    additionalSkills: 'Additional Skills',
    languages: 'Foreign Languages',
    other: 'Additional Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    dateOfBirth: 'Date of Birth',
    address: 'Address',
    phone: 'Phone',
    email: 'Email',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Website',
    institution: 'Institution Name',
    field: 'Field / Specialization',
    employer: 'Employer',
    city: 'City',
    country: 'Country',
    jobTitle: 'Job Title',
    jobDescription: 'Job Description',
    languageName: 'Language',
    level: 'Level',
    driversLicense: "Driver's License",
    relocation: 'Willing to relocate',
    availability: 'Immediately Available',
    addEducation: 'Add Education',
    addWork: 'Add Work Experience',
    addSkill: 'Add Skill',
    addLanguage: 'Add Language',
    addOther: 'Add Information',
    preview: 'Preview',
    downloadPdf: 'Download PDF',
    from: 'From',
    to: 'To',
    present: 'Present',
    currently: 'Current',
    saved: 'Saved',
    saving: 'Saving...',
    notSaved: 'Not saved',
    incognitoWarning: 'You are in private mode — data will not be saved after closing the window.',
    datePlaceholder: 'MM/DD/YYYY',
    confirmDeleteTitle: 'Confirm Deletion',
    confirmDeleteMessage: 'Are you sure you want to delete this entry?',
    confirmDeleteAction: 'Delete',
    cancelAction: 'Cancel',
    livePreview: 'Live Preview',
    selectTemplate: 'Select Template',
    modern: 'Modern',
    classic: 'Classic',
    minimalist: 'Minimalist',
  },
  'sv': {
    title: 'Curriculum Vitae',
    personalInfo: 'Personlig information',
    education: 'Utbildning',
    workExperience: 'Arbetslivserfarenhet',
    skills: 'Färdigheter',
    itSkills: 'IT-färdigheter',
    additionalSkills: 'Övriga färdigheter',
    languages: 'Språk',
    other: 'Övrig information',
    firstName: 'Förnamn',
    lastName: 'Efternamn',
    dateOfBirth: 'Födelsedatum',
    address: 'Adress',
    phone: 'Telefon',
    email: 'E-post',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Webbplats',
    institution: 'Institution',
    field: 'Inriktning',
    employer: 'Arbetsgivare',
    city: 'Stad',
    country: 'Land',
    jobTitle: 'Yrke',
    jobDescription: 'Arbetsbeskrivning',
    languageName: 'Språk',
    level: 'Nivå',
    driversLicense: 'Körkort',
    relocation: 'Villig att flytta',
    availability: 'Tillgänglig omedelbart',
    addEducation: 'Lägg till utbildning',
    addWork: 'Lägg till arbetserfarenhet',
    addSkill: 'Lägg till färdighet',
    addLanguage: 'Lägg till språk',
    addOther: 'Lägg till information',
    preview: 'Förhandsgranskning',
    downloadPdf: 'Ladda ner PDF',
    from: 'Från',
    to: 'Till',
    present: 'Nuvarande',
    currently: 'Nuvarande',
    saved: 'Sparad',
    saving: 'Sparar...',
    notSaved: 'Ej sparad',
    incognitoWarning: 'Du är i inkognitoläge — data sparas inte efter att fönstret stängs.',
    autoGenerate: 'Autogenerera (AI)',
    generating: 'Genererar...',
    datePlaceholder: 'YYYY-MM-DD',
    confirmDeleteTitle: 'Bekräfta borttagning',
    confirmDeleteMessage: 'Är du säker på att du vill ta bort den här posten?',
    confirmDeleteAction: 'Ta bort',
    cancelAction: 'Avbryt',
    livePreview: 'Live-förhandsvisning',
  },
  'de': {
    title: 'Lebenslauf',
    personalInfo: 'Persönliche Informationen',
    education: 'Ausbildung',
    workExperience: 'Berufserfahrung',
    skills: 'Fähigkeiten',
    itSkills: 'IT-Kenntnisse',
    additionalSkills: 'Weitere Fähigkeiten',
    languages: 'Sprachen',
    other: 'Zusätzliche Informationen',
    firstName: 'Vorname',
    lastName: 'Nachname',
    dateOfBirth: 'Geburtsdatum',
    address: 'Adresse',
    phone: 'Telefon',
    email: 'E-Mail',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Webseite',
    institution: 'Institution',
    field: 'Fachrichtung',
    employer: 'Arbeitgeber',
    city: 'Stadt',
    country: 'Land',
    jobTitle: 'Berufsbezeichnung',
    jobDescription: 'Stellenbeschreibung',
    languageName: 'Sprache',
    level: 'Niveau',
    driversLicense: 'Führerschein',
    relocation: 'Umzugsbereit',
    availability: 'Sofort verfügbar',
    addEducation: 'Ausbildung hinzufügen',
    addWork: 'Berufserfahrung hinzufügen',
    addSkill: 'Fähigkeit hinzufügen',
    addLanguage: 'Sprache hinzufügen',
    addOther: 'Information hinzufügen',
    preview: 'Vorschau',
    downloadPdf: 'PDF herunterladen',
    from: 'Von',
    to: 'Bis',
    present: 'Derzeit',
    currently: 'Derzeit',
    saved: 'Gespeichert',
    saving: 'Speichert...',
    notSaved: 'Nicht gespeichert',
    incognitoWarning: 'Sie befinden sich im Inkognito-Modus — Daten werden nach dem Schließen des Fensters nicht gespeichert.',
    autoGenerate: 'Automatisch generieren (AI)',
    generating: 'Generiere...',
    datePlaceholder: 'TT.MM.JJJJ',
    confirmDeleteTitle: 'Löschen bestätigen',
    confirmDeleteMessage: 'Sind Sie sicher, dass Sie diesen Eintrag löschen möchten?',
    confirmDeleteAction: 'Löschen',
    cancelAction: 'Abbrechen',
    livePreview: 'Live-Vorschau',
  },
  'es': {
    title: 'Currículum Vítae',
    personalInfo: 'Información Personal',
    education: 'Educación',
    workExperience: 'Experiencia Laboral',
    skills: 'Habilidades',
    itSkills: 'Habilidades IT',
    additionalSkills: 'Habilidades Adicionales',
    languages: 'Idiomas',
    other: 'Información Adicional',
    firstName: 'Nombre',
    lastName: 'Apellido',
    dateOfBirth: 'Fecha de Nacimiento',
    address: 'Dirección',
    phone: 'Teléfono',
    email: 'Correo electrónico',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Sitio web',
    institution: 'Institución',
    field: 'Campo / Especialización',
    employer: 'Empleador',
    city: 'Ciudad',
    country: 'País',
    jobTitle: 'Título del puesto',
    jobDescription: 'Descripción del trabajo',
    languageName: 'Idioma',
    level: 'Nivel',
    driversLicense: 'Licencia de conducir',
    relocation: 'Dispuesto a mudarse',
    availability: 'Disponibilidad inmediata',
    addEducation: 'Añadir educación',
    addWork: 'Añadir experiencia laboral',
    addSkill: 'Añadir habilidad',
    addLanguage: 'Añadir idioma',
    addOther: 'Añadir información',
    preview: 'Vista previa',
    downloadPdf: 'Descargar PDF',
    from: 'Desde',
    to: 'Hasta',
    present: 'Actualidad',
    currently: 'Actual',
    saved: 'Guardado',
    saving: 'Guardando...',
    notSaved: 'No guardado',
    incognitoWarning: 'Estás en modo incógnito — los datos no se guardarán después de cerrar la ventana.',
    autoGenerate: 'Autogenerar (AI)',
    generating: 'Generando...',
    datePlaceholder: 'DD/MM/AAAA',
    confirmDeleteTitle: 'Confirmar eliminación',
    confirmDeleteMessage: '¿Estás seguro de que deseas eliminar esta entrada?',
    confirmDeleteAction: 'Eliminar',
    cancelAction: 'Cancelar',
    livePreview: 'Vista previa en vivo',
  },
  'ar': {
    title: 'السيرة الذاتية',
    personalInfo: 'المعلومات الشخصية',
    education: 'التعليم',
    workExperience: 'الخبرة العملية',
    skills: 'المهارات',
    itSkills: 'مهارات تقنية المعلومات',
    additionalSkills: 'مهارات إضافية',
    languages: 'اللغات',
    other: 'معلومات إضافية',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    dateOfBirth: 'تاريخ الميلاد',
    address: 'العنوان',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'الموقع الإلكتروني',
    institution: 'اسم المؤسسة',
    field: 'المجال / التخصص',
    employer: 'صاحب العمل',
    city: 'المدينة',
    country: 'البلد',
    jobTitle: 'المسمى الوظيفي',
    jobDescription: 'الوصف الوظيفي',
    languageName: 'اللغة',
    level: 'المستوى',
    driversLicense: 'رخصة القيادة',
    relocation: 'مستعد للانتقال',
    availability: 'متاح فوراً',
    addEducation: 'إضافة تعليم',
    addWork: 'إضافة خبرة عملية',
    addSkill: 'إضافة مهارة',
    addLanguage: 'إضافة لغة',
    addOther: 'إضافة معلومات',
    preview: 'معاينة',
    downloadPdf: 'تحميل PDF',
    from: 'من',
    to: 'إلى',
    present: 'حتى الآن',
    currently: 'حاليا',
    saved: 'تم الحفظ',
    saving: 'جاري الحفظ...',
    notSaved: 'لم يتم الحفظ',
    incognitoWarning: 'أنت في وضع التصفح الخفي — لن يتم حفظ البيانات بعد إغلاق النافذة.',
    autoGenerate: 'توليد تلقائي (AI)',
    generating: 'جاري التوليد...',
    datePlaceholder: 'DD/MM/YYYY',
    confirmDeleteTitle: 'تأكيد الحذف',
    confirmDeleteMessage: 'هل أنت متأكد أنك تريد حذف هذا الإدخال؟',
    confirmDeleteAction: 'حذف',
    cancelAction: 'إلغاء',
    livePreview: 'معاينة مباشرة',
  },
  'he': {
    title: 'קורות חיים',
    personalInfo: 'מידע אישי',
    education: 'השכלה',
    workExperience: 'ניסיון תעסוקתי',
    skills: 'כישורים',
    itSkills: 'כישורי IT',
    additionalSkills: 'כישורים נוספים',
    languages: 'שפות',
    other: 'מידע נוסף',
    firstName: 'שם פרטי',
    lastName: 'שם משפחה',
    dateOfBirth: 'תאריך לידה',
    address: 'כתובת',
    phone: 'טלפון',
    email: 'אימייל',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'אתר אינטרנט',
    institution: 'שם המוסד',
    field: 'תחום / התמחות',
    employer: 'מעסיק',
    city: 'עיר',
    country: 'מדינה',
    jobTitle: 'תיאור תפקיד',
    jobDescription: 'תיאור העבודה',
    languageName: 'שפה',
    level: 'רמה',
    driversLicense: 'רישיון נהיגה',
    relocation: 'מוכן למעבר',
    availability: 'זמין מיידית',
    addEducation: 'הוסף השכלה',
    addWork: 'הוסף ניסיון תעסוקתי',
    addSkill: 'הוסף כישור',
    addLanguage: 'הוסף שפה',
    addOther: 'הוסף מידע',
    preview: 'תצוגה מקדימה',
    downloadPdf: 'הורד PDF',
    from: 'מ-',
    to: 'עד',
    present: 'כיום',
    currently: 'נוכחי',
    saved: 'נשמר',
    saving: 'שומר...',
    notSaved: 'לא נשמר',
    incognitoWarning: 'אתה במצב גלישה בסתר — המידע לא יישמר לאחר סגירת החלון.',
    autoGenerate: 'יצירה אוטומטית (AI)',
    generating: 'יוצר...',
    datePlaceholder: 'DD/MM/YYYY',
    confirmDeleteTitle: 'אישור מחיקה',
    confirmDeleteMessage: 'האם אתה בטוח שברצונך למחוק פריט זה?',
    confirmDeleteAction: 'מחק',
    cancelAction: 'ביטול',
    livePreview: 'תצוגה מקדימה חיה',
  },
  'tr': {
    title: 'Özgeçmiş',
    personalInfo: 'Kişisel Bilgiler',
    education: 'Eğitim',
    workExperience: 'İş Deneyimi',
    skills: 'Yetenekler',
    itSkills: 'BT Yetenekleri',
    additionalSkills: 'Ek Yetenekler',
    languages: 'Diller',
    other: 'Ek Bilgiler',
    firstName: 'Ad',
    lastName: 'Soyad',
    dateOfBirth: 'Doğum Tarihi',
    address: 'Adres',
    phone: 'Telefon',
    email: 'E-posta',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Web Sitesi',
    institution: 'Kurum Adı',
    field: 'Bölüm / Uzmanlık',
    employer: 'İşveren',
    city: 'Şehir',
    country: 'Ülke',
    jobTitle: 'İş Unvanı',
    jobDescription: 'İş Tanımı',
    languageName: 'Dil',
    level: 'Seviye',
    driversLicense: 'Ehliyet',
    relocation: 'Taşınmaya uygun',
    availability: 'Hemen başlayabilir',
    addEducation: 'Eğitim Ekle',
    addWork: 'İş Deneyimi Ekle',
    addSkill: 'Yetenek Ekle',
    addLanguage: 'Dil Ekle',
    addOther: 'Bilgi Ekle',
    preview: 'Önizleme',
    downloadPdf: 'PDF İndir',
    from: 'Başlangıç',
    to: 'Bitiş',
    present: 'Devam ediyor',
    currently: 'Şu anda',
    saved: 'Kaydedildi',
    saving: 'Kaydediliyor...',
    notSaved: 'Kaydedilmedi',
    incognitoWarning: 'Gizli moddasınız — pencere kapatıldıktan sonra veriler kaydedilmeyecektir.',
    autoGenerate: 'Otomatik oluştur (AI)',
    generating: 'Oluşturuluyor...',
    datePlaceholder: 'GG.AA.YYYY',
    confirmDeleteTitle: 'Silme İşlemini Onayla',
    confirmDeleteMessage: 'Bu girişi silmek istediğinizden emin misiniz?',
    confirmDeleteAction: 'Sil',
    cancelAction: 'İptal',
    livePreview: 'Canlı Önizleme',
  },
  'fr': {
    title: 'Curriculum Vitae',
    personalInfo: 'Informations Personnelles',
    education: 'Éducation',
    workExperience: 'Expérience Professionnelle',
    skills: 'Compétences',
    itSkills: 'Compétences Informatiques',
    additionalSkills: 'Compétences Additionnelles',
    languages: 'Langues Étrangères',
    other: 'Informations Complémentaires',
    firstName: 'Prénom',
    lastName: 'Nom',
    dateOfBirth: 'Date de Naissance',
    address: 'Adresse',
    phone: 'Téléphone',
    email: 'Email',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Site Web',
    institution: 'Nom de l\'Institution',
    field: 'Domaine / Spécialisation',
    employer: 'Employeur',
    city: 'Ville',
    country: 'Pays',
    jobTitle: 'Titre du Poste',
    jobDescription: 'Description du Poste',
    languageName: 'Langue',
    level: 'Niveau',
    driversLicense: 'Permis de Conduire',
    relocation: 'Prêt à déménager',
    availability: 'Disponible Immédiatement',
    addEducation: 'Ajouter une Éducation',
    addWork: 'Ajouter une Expérience',
    addSkill: 'Ajouter une Compétence',
    addLanguage: 'Ajouter une Langue',
    addOther: 'Ajouter une Information',
    preview: 'Aperçu',
    downloadPdf: 'Télécharger PDF',
    from: 'De',
    to: 'À',
    present: 'Présent',
    currently: 'Actuel',
    saved: 'Enregistré',
    saving: 'Enregistrement...',
    notSaved: 'Non enregistré',
    incognitoWarning: 'Vous êtes en mode incognito — les données ne seront pas sauvegardées après la fermeture de la fenêtre.',
    autoGenerate: 'Générer automatiquement (AI)',
    generating: 'Génération...',
    datePlaceholder: 'JJ/MM/AAAA',
    confirmDeleteTitle: 'Confirmer la suppression',
    confirmDeleteMessage: 'Êtes-vous sûr de vouloir supprimer cette entrée ?',
    confirmDeleteAction: 'Supprimer',
    cancelAction: 'Annuler',
    livePreview: 'Aperçu en direct',
  },
  'it': {
    title: 'Curriculum Vitae',
    personalInfo: 'Informazioni Personali',
    education: 'Istruzione',
    workExperience: 'Esperienza Lavorativa',
    skills: 'Competenze',
    itSkills: 'Competenze IT',
    additionalSkills: 'Altre Competenze',
    languages: 'Lingue Straniere',
    other: 'Informazioni Aggiuntive',
    firstName: 'Nome',
    lastName: 'Cognome',
    dateOfBirth: 'Data di Nascita',
    address: 'Indirizzo',
    phone: 'Telefono',
    email: 'Email',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Sito Web',
    institution: 'Nome dell\'Istituto',
    field: 'Campo / Specializzazione',
    employer: 'Datore di Lavoro',
    city: 'Città',
    country: 'Paese',
    jobTitle: 'Titolo di Lavoro',
    jobDescription: 'Descrizione del Lavoro',
    languageName: 'Lingua',
    level: 'Livello',
    driversLicense: 'Patente di Guida',
    relocation: 'Disponibile al trasferimento',
    availability: 'Disponibile Immediatamente',
    addEducation: 'Aggiungi Istruzione',
    addWork: 'Aggiungi Esperienza',
    addSkill: 'Aggiungi Competenza',
    addLanguage: 'Aggiungi Lingua',
    addOther: 'Aggiungi Informazione',
    preview: 'Anteprima',
    downloadPdf: 'Scarica PDF',
    from: 'Da',
    to: 'A',
    present: 'Attuale',
    currently: 'Attuale',
    saved: 'Salvato',
    saving: 'Salvataggio...',
    notSaved: 'Non salvato',
    incognitoWarning: 'Sei in modalità incognito — i dati non verranno salvati dopo la chiusura della finestra.',
    autoGenerate: 'Genera automaticamente (AI)',
    generating: 'Generazione...',
    datePlaceholder: 'GG/MM/AAAA',
    confirmDeleteTitle: 'Conferma eliminazione',
    confirmDeleteMessage: 'Sei sicuro di voler eliminare questa voce?',
    confirmDeleteAction: 'Elimina',
    cancelAction: 'Annulla',
    livePreview: 'Anteprima dal vivo',
  },
  'pt': {
    title: 'Curriculum Vitae',
    personalInfo: 'Informações Pessoais',
    education: 'Educação',
    workExperience: 'Experiência Profissional',
    skills: 'Habilidades',
    itSkills: 'Habilidades de TI',
    additionalSkills: 'Habilidades Adicionais',
    languages: 'Idiomas Estrangeiros',
    other: 'Informações Adicionais',
    firstName: 'Nome',
    lastName: 'Sobrenome',
    dateOfBirth: 'Data de Nascimento',
    address: 'Endereço',
    phone: 'Telefone',
    email: 'E-mail',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Site',
    institution: 'Nome da Instituição',
    field: 'Campo / Especialização',
    employer: 'Empregador',
    city: 'Cidade',
    country: 'País',
    jobTitle: 'Título do Cargo',
    jobDescription: 'Descrição do Cargo',
    languageName: 'Idioma',
    level: 'Nível',
    driversLicense: 'Carteira de Habilitação',
    relocation: 'Disponível para recolocação',
    availability: 'Disponibilidade Imediata',
    addEducation: 'Adicionar Educação',
    addWork: 'Adicionar Experiência',
    addSkill: 'Adicionar Habilidade',
    addLanguage: 'Adicionar Idioma',
    addOther: 'Adicionar Informação',
    preview: 'Visualização',
    downloadPdf: 'Baixar PDF',
    from: 'De',
    to: 'Até',
    present: 'Atual',
    currently: 'Atual',
    saved: 'Salvo',
    saving: 'Salvando...',
    notSaved: 'Não salvo',
    incognitoWarning: 'Você está no modo incógnito — os dados não serão salvos após o fechamento da janela.',
    autoGenerate: 'Gerar automaticamente (AI)',
    generating: 'Gerando...',
    datePlaceholder: 'DD/MM/AAAA',
    confirmDeleteTitle: 'Confirmar Exclusão',
    confirmDeleteMessage: 'Tem certeza de que deseja excluir esta entrada?',
    confirmDeleteAction: 'Excluir',
    cancelAction: 'Cancelar',
    livePreview: 'Visualização ao vivo',
  },
  'ru': {
    title: 'Резюме',
    personalInfo: 'Личная информация',
    education: 'Образование',
    workExperience: 'Опыт работы',
    skills: 'Навыки',
    itSkills: 'ИТ-навыки',
    additionalSkills: 'Дополнительные навыки',
    languages: 'Иностранные языки',
    other: 'Дополнительная информация',
    firstName: 'Имя',
    lastName: 'Фамилия',
    dateOfBirth: 'Дата рождения',
    address: 'Адрес',
    phone: 'Телефон',
    email: 'Электронная почта',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Веб-сайт',
    institution: 'Название учебного заведения',
    field: 'Специальность',
    employer: 'Работодатель',
    city: 'Город',
    country: 'Страна',
    jobTitle: 'Должность',
    jobDescription: 'Описание работы',
    languageName: 'Язык',
    level: 'Уровень',
    driversLicense: 'Водительское удостоверение',
    relocation: 'Готовность к переезду',
    availability: 'Готов приступить немедленно',
    addEducation: 'Добавить образование',
    addWork: 'Добавить опыт работы',
    addSkill: 'Добавить навык',
    addLanguage: 'Добавить язык',
    addOther: 'Добавить информацию',
    preview: 'Предпросмотр',
    downloadPdf: 'Скачать PDF',
    from: 'С',
    to: 'По',
    present: 'по настоящее время',
    currently: 'текущее',
    saved: 'Сохранено',
    saving: 'Сохранение...',
    notSaved: 'Не сохранено',
    incognitoWarning: 'Вы находитесь в режиме инкогнито — данные не будут сохранены после закрытия окна.',
    autoGenerate: 'Автогенерация (AI)',
    generating: 'Генерация...',
    datePlaceholder: 'ДД.ММ.ГГГГ',
    confirmDeleteTitle: 'Подтверждение удаления',
    confirmDeleteMessage: 'Вы уверены, что хотите удалить эту запись?',
    confirmDeleteAction: 'Удалить',
    cancelAction: 'Отмена',
    livePreview: 'Живой предпросмотр',
  },
  'zh': {
    title: '个人简历',
    personalInfo: '个人信息',
    education: '教育经历',
    workExperience: '工作经验',
    skills: '技能',
    itSkills: 'IT技能',
    additionalSkills: '其他技能',
    languages: '外语',
    other: '其他信息',
    firstName: '名',
    lastName: '姓',
    dateOfBirth: '出生日期',
    address: '地址',
    phone: '电话',
    email: '电子邮件',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: '网站',
    institution: '机构名称',
    field: '专业/领域',
    employer: '雇主',
    city: '城市',
    country: '国家',
    jobTitle: '职位名称',
    jobDescription: '工作描述',
    languageName: '语言',
    level: '水平',
    driversLicense: '驾照',
    relocation: '愿意搬迁',
    availability: '立即到岗',
    addEducation: '添加教育',
    addWork: '添加工作经验',
    addSkill: '添加技能',
    addLanguage: '添加语言',
    addOther: '添加信息',
    preview: '预览',
    downloadPdf: '下载 PDF',
    from: '从',
    to: '至',
    present: '至今',
    currently: '当前',
    saved: '已保存',
    saving: '保存中...',
    notSaved: '未保存',
    incognitoWarning: '您处于无痕模式 — 关闭窗口后数据将不会被保存。',
    autoGenerate: '自动生成 (AI)',
    generating: '生成中...',
    datePlaceholder: 'YYYY/MM/DD',
    confirmDeleteTitle: '确认删除',
    confirmDeleteMessage: '您确定要删除此条目吗？',
    confirmDeleteAction: '删除',
    cancelAction: '取消',
    livePreview: '实时预览',
  },
  'ja': {
    title: '履歴書',
    personalInfo: '基本情報',
    education: '学歴',
    workExperience: '職歴',
    skills: 'スキル',
    itSkills: 'ITスキル',
    additionalSkills: 'その他のスキル',
    languages: '外国語',
    other: 'その他',
    firstName: '名',
    lastName: '姓',
    dateOfBirth: '生年月日',
    address: '住所',
    phone: '電話番号',
    email: 'メールアドレス',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'ウェブサイト',
    institution: '学校・機関名',
    field: '学部・学科・専攻',
    employer: '勤務先',
    city: '市区町村',
    country: '国',
    jobTitle: '職種',
    jobDescription: '業務内容',
    languageName: '言語',
    level: 'レベル',
    driversLicense: '運転免許',
    relocation: '転居可能',
    availability: '即日勤務可能',
    addEducation: '学歴を追加',
    addWork: '職歴を追加',
    addSkill: 'スキルを追加',
    addLanguage: '言語を追加',
    addOther: '情報を追加',
    preview: 'プレビュー',
    downloadPdf: 'PDFをダウンロード',
    from: '開始',
    to: '終了',
    present: '現在',
    currently: '現在',
    saved: '保存済み',
    saving: '保存中...',
    notSaved: '保存されていません',
    incognitoWarning: 'シークレットモードです。ウィンドウを閉じるとデータは保存されません。',
    autoGenerate: 'AIで自動生成',
    generating: '生成中...',
    datePlaceholder: 'YYYY/MM/DD',
    confirmDeleteTitle: '削除の確認',
    confirmDeleteMessage: 'この項目を削除してもよろしいですか？',
    confirmDeleteAction: '削除',
    cancelAction: 'キャンセル',
    livePreview: 'ライブプレビュー',
  },
  'ko': {
    title: '이력서',
    personalInfo: '개인 정보',
    education: '학력',
    workExperience: '경력 사항',
    skills: '기술',
    itSkills: 'IT 기술',
    additionalSkills: '추가 기술',
    languages: '외국어',
    other: '기타 정보',
    firstName: '이름',
    lastName: '성',
    dateOfBirth: '생년월일',
    address: '주소',
    phone: '전화번호',
    email: '이메일',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: '웹사이트',
    institution: '학교/기관명',
    field: '전공/분야',
    employer: '직장명',
    city: '도시',
    country: '국가',
    jobTitle: '직책',
    jobDescription: '업무 내용',
    languageName: '언어',
    level: '수준',
    driversLicense: '운전면허',
    relocation: '이전 가능',
    availability: '즉시 근무 가능',
    addEducation: '학력 추가',
    addWork: '경력 추가',
    addSkill: '기술 추가',
    addLanguage: '언어 추가',
    addOther: '정보 추가',
    preview: '미리보기',
    downloadPdf: 'PDF 다운로드',
    from: '시작',
    to: '종료',
    present: '현재',
    currently: '현재',
    saved: '저장됨',
    saving: '저장 중...',
    notSaved: '저장되지 않음',
    incognitoWarning: '시크릿 모드입니다. 창을 닫으면 데이터가 저장되지 않습니다.',
    autoGenerate: 'AI 자동 생성',
    generating: '생성 중...',
    datePlaceholder: 'YYYY/MM/DD',
    confirmDeleteTitle: '삭제 확인',
    confirmDeleteMessage: '이 항목을 삭제하시겠습니까?',
    confirmDeleteAction: '삭제',
    cancelAction: '취소',
    livePreview: '실시간 미리보기',
  },
  'nl': {
    title: 'Curriculum Vitae',
    personalInfo: 'Persoonlijke Informatie',
    education: 'Opleiding',
    workExperience: 'Werkervaring',
    skills: 'Vaardigheden',
    itSkills: 'IT-vaardigheden',
    additionalSkills: 'Aanvullende Vaardigheden',
    languages: 'Talen',
    other: 'Aanvullende Informatie',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    dateOfBirth: 'Geboortedatum',
    address: 'Adres',
    phone: 'Telefoon',
    email: 'E-mail',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Website',
    institution: 'Naam Instelling',
    field: 'Richting / Specialisatie',
    employer: 'Werkgever',
    city: 'Stad',
    country: 'Land',
    jobTitle: 'Functie',
    jobDescription: 'Functieomschrijving',
    languageName: 'Taal',
    level: 'Niveau',
    driversLicense: 'Rijbewijs',
    relocation: 'Bereid om te verhuizen',
    availability: 'Per direct beschikbaar',
    addEducation: 'Opleiding Toevoegen',
    addWork: 'Werkervaring Toevoegen',
    addSkill: 'Vaardigheid Toevoegen',
    addLanguage: 'Taal Toevoegen',
    addOther: 'Informatie Toevoegen',
    preview: 'Voorbeeld',
    downloadPdf: 'Download PDF',
    from: 'Van',
    to: 'Tot',
    present: 'Heden',
    currently: 'Huidig',
    saved: 'Opgeslagen',
    saving: 'Opslaan...',
    notSaved: 'Niet opgeslagen',
    incognitoWarning: 'U bevindt zich in de incognitomodus — gegevens worden niet opgeslagen na het sluiten van het venster.',
    autoGenerate: 'Automatisch genereren (AI)',
    generating: 'Genereren...',
    datePlaceholder: 'DD-MM-JJJJ',
    confirmDeleteTitle: 'Verwijderen Bevestigen',
    confirmDeleteMessage: 'Weet u zeker dat u dit item wilt verwijderen?',
    confirmDeleteAction: 'Verwijderen',
    cancelAction: 'Annuleren',
    livePreview: 'Live Voorbeeld',
  },
  'pl': {
    title: 'Curriculum Vitae',
    personalInfo: 'Informacje Osobiste',
    education: 'Wykształcenie',
    workExperience: 'Doświadczenie Zawodowe',
    skills: 'Umiejętności',
    itSkills: 'Umiejętności IT',
    additionalSkills: 'Dodatkowe Umiejętności',
    languages: 'Języki Obce',
    other: 'Dodatkowe Informacje',
    firstName: 'Imię',
    lastName: 'Nazwisko',
    dateOfBirth: 'Data Urodzenia',
    address: 'Adres',
    phone: 'Telefon',
    email: 'E-mail',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Strona WWW',
    institution: 'Nazwa Instytucji',
    field: 'Kierunek / Specjalizacja',
    employer: 'Pracodawca',
    city: 'Miasto',
    country: 'Kraj',
    jobTitle: 'Stanowisko',
    jobDescription: 'Opis Stanowiska',
    languageName: 'Język',
    level: 'Poziom',
    driversLicense: 'Prawo Jazdy',
    relocation: 'Gotowość do relokacji',
    availability: 'Dostępność od zaraz',
    addEducation: 'Dodaj Wykształcenie',
    addWork: 'Dodaj Doświadczenie',
    addSkill: 'Dodaj Umiejętność',
    addLanguage: 'Dodaj Język',
    addOther: 'Dodaj Informację',
    preview: 'Podgląd',
    downloadPdf: 'Pobierz PDF',
    from: 'Od',
    to: 'Do',
    present: 'Obecnie',
    currently: 'Obecnie',
    saved: 'Zapisano',
    saving: 'Zapisywanie...',
    notSaved: 'Nie zapisano',
    incognitoWarning: 'Jesteś в trybie incognito — dane nie zostaną zapisane po zamknięciu okna.',
    autoGenerate: 'Generuj automatycznie (AI)',
    generating: 'Generowanie...',
    datePlaceholder: 'DD.MM.RRRR',
    confirmDeleteTitle: 'Potwierdź Usunięcie',
    confirmDeleteMessage: 'Czy na pewno chcesz usunąć ten wpis?',
    confirmDeleteAction: 'Usuń',
    cancelAction: 'Anuluj',
    livePreview: 'Podgląd na żywo',
  },
};

export const LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'Native'];

export const SKILLS_SUGGESTIONS = {
  it: [
    'JavaScript', 'TypeScript', 'React', 'Node.js', 'Python', 'Java', 'C++', 'C#', '.NET',
    'SQL', 'MongoDB', 'PostgreSQL', 'Docker', 'Kubernetes', 'AWS', 'Azure', 'Google Cloud',
    'Git', 'GitHub', 'HTML5', 'CSS3', 'Tailwind CSS', 'Sass', 'Next.js', 'Vue.js', 'Angular',
    'PHP', 'Laravel', 'Express.js', 'Redux', 'GraphQL', 'REST API', 'Linux', 'Bash',
    'Machine Learning', 'Data Science', 'UI/UX Design', 'Figma', 'Adobe XD', 'Photoshop'
  ],
  additional: [
    'Project Management', 'Agile', 'Scrum', 'Team Leadership', 'Public Speaking',
    'Technical Writing', 'Problem Solving', 'Critical Thinking', 'Time Management',
    'Communication', 'Negotiation', 'Strategic Planning', 'Customer Service',
    'Bilingual', 'Multilingual', 'Analytical Thinking', 'Decision Making',
    'Adaptability', 'Creativity', 'Conflict Resolution', 'Emotional Intelligence'
  ],
  languages: [
    'English', 'Spanish', 'French', 'German', 'Italian', 'Portuguese', 'Russian',
    'Chinese', 'Japanese', 'Korean', 'Arabic', 'Turkish', 'Hebrew', 'Serbian', 'Croatian',
    'Bosnian', 'Slovenian', 'Macedonian', 'Dutch', 'Polish', 'Swedish', 'Norwegian'
  ],
  jobTitles: [
    'Software Engineer', 'Frontend Developer', 'Backend Developer', 'Full Stack Developer',
    'Mobile App Developer', 'DevOps Engineer', 'Data Scientist', 'Data Analyst',
    'UI/UX Designer', 'Product Manager', 'Project Manager', 'Business Analyst',
    'Marketing Manager', 'Sales Representative', 'Customer Success Manager',
    'Human Resources Manager', 'Accountant', 'Financial Analyst', 'Operations Manager',
    'Content Writer', 'Copywriter', 'Social Media Manager', 'SEO Specialist'
  ]
};
